# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T17:35:56+00:00



import argparse
import json
import os
from datetime import datetime
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import (
    APIKeyHeader,
    BaseSecurity,
    UnsuportedSecurityStub,
)
from fastapi import Path, Query

from models import (
    AppApiUsageApplicationIdGetResponse,
    AppFirstPartyGetResponse,
    CommunityContentGetSortMediaFilterPageGetResponse,
    Components,
    ContentGetContentByIdIdLocaleGetResponse,
    ContentGetContentByTagAndTypeTagTypeLocaleGetResponse,
    ContentGetContentTypeTypeGetResponse,
    ContentRssNewsArticlesPageTokenGetResponse,
    ContentSearchContentByTagAndTypeTagTypeLocaleGetResponse,
    ContentSearchHelpArticlesSearchtextSizeGetResponse,
    ContentSearchLocaleGetResponse,
    Destiny2ActionsItemsEquipItemPostResponse,
    Destiny2ActionsItemsEquipItemsPostResponse,
    Destiny2ActionsItemsInsertSocketPlugFreePostResponse,
    Destiny2ActionsItemsInsertSocketPlugPostResponse,
    Destiny2ActionsItemsPullFromPostmasterPostResponse,
    Destiny2ActionsItemsSetLockStatePostResponse,
    Destiny2ActionsItemsSetTrackedStatePostResponse,
    Destiny2ActionsItemsTransferItemPostResponse,
    Destiny2ActionsLoadoutsClearLoadoutPostResponse,
    Destiny2ActionsLoadoutsEquipLoadoutPostResponse,
    Destiny2ActionsLoadoutsSnapshotLoadoutPostResponse,
    Destiny2ActionsLoadoutsUpdateLoadoutIdentifiersPostResponse,
    Destiny2ArmorySearchTypeSearchTermGetResponse,
    Destiny2AwaAwaProvideAuthorizationResultPostResponse,
    Destiny2AwaGetActionTokenCorrelationIdGetResponse,
    Destiny2AwaInitializePostResponse,
    Destiny2ClanClanBannerDictionaryGetResponse,
    Destiny2ClanGroupIdWeeklyRewardStateGetResponse,
    Destiny2ManifestEntityTypeHashIdentifierGetResponse,
    Destiny2ManifestGetResponse,
    Destiny2MembershipTypeAccountDestinyMembershipIdCharacterCharacterIdStatsActivitiesGetResponse,
    Destiny2MembershipTypeAccountDestinyMembershipIdCharacterCharacterIdStatsAggregateActivityStatsGetResponse,
    Destiny2MembershipTypeAccountDestinyMembershipIdCharacterCharacterIdStatsGetResponse,
    Destiny2MembershipTypeAccountDestinyMembershipIdCharacterCharacterIdStatsUniqueWeaponsGetResponse,
    Destiny2MembershipTypeAccountDestinyMembershipIdStatsGetResponse,
    Destiny2MembershipTypeAccountDestinyMembershipIdStatsLeaderboardsGetResponse,
    Destiny2MembershipTypeProfileDestinyMembershipIdCharacterCharacterIdCollectiblesCollectiblePresentationNodeHashGetResponse,
    Destiny2MembershipTypeProfileDestinyMembershipIdCharacterCharacterIdGetResponse,
    Destiny2MembershipTypeProfileDestinyMembershipIdCharacterCharacterIdVendorsGetResponse,
    Destiny2MembershipTypeProfileDestinyMembershipIdCharacterCharacterIdVendorsVendorHashGetResponse,
    Destiny2MembershipTypeProfileDestinyMembershipIdGetResponse,
    Destiny2MembershipTypeProfileDestinyMembershipIdItemItemInstanceIdGetResponse,
    Destiny2MembershipTypeProfileMembershipIdLinkedProfilesGetResponse,
    Destiny2MilestonesGetResponse,
    Destiny2MilestonesMilestoneHashContentGetResponse,
    Destiny2SearchDestinyPlayerByBungieNameMembershipTypePostResponse,
    Destiny2StatsAggregateClanStatsGroupIdGetResponse,
    Destiny2StatsDefinitionGetResponse,
    Destiny2StatsLeaderboardsClansGroupIdGetResponse,
    Destiny2StatsLeaderboardsMembershipTypeDestinyMembershipIdCharacterIdGetResponse,
    Destiny2StatsPostGameCarnageReportActivityIdGetResponse,
    Destiny2StatsPostGameCarnageReportActivityIdReportPostResponse,
    Destiny2VendorsGetResponse,
    FireteamClanGroupIdActiveCountGetResponse,
    FireteamClanGroupIdAvailablePlatformActivityTypeDateRangeSlotFilterPublicOnlyPageGetResponse,
    FireteamClanGroupIdMyPlatformIncludeClosedPageGetResponse,
    FireteamClanGroupIdSummaryFireteamIdGetResponse,
    FireteamSearchAvailablePlatformActivityTypeDateRangeSlotFilterPageGetResponse,
    ForumGetCoreTopicsPagedPageSortQuickDateCategoryFilterGetResponse,
    ForumGetForumTagSuggestionsGetResponse,
    ForumGetPostAndParentAwaitingApprovalChildPostIdGetResponse,
    ForumGetPostAndParentChildPostIdGetResponse,
    ForumGetPostsThreadedPagedFromChildChildPostIdPagePageSizeReplySizeRootThreadModeSortModeGetResponse,
    ForumGetPostsThreadedPagedParentPostIdPagePageSizeReplySizeGetParentPostRootThreadModeSortModeGetResponse,
    ForumGetTopicForContentContentIdGetResponse,
    ForumGetTopicsPagedPagePageSizeGroupSortQuickDateCategoryFilterGetResponse,
    ForumPollTopicIdGetResponse,
    ForumRecruitSummariesPostResponse,
    GetAvailableLocalesGetResponse,
    GlobalAlertsGetResponse,
    Groups,
    GroupV2GetAvailableAvatarsGetResponse,
    GroupV2GetAvailableThemesGetResponse,
    GroupV2GetUserClanInviteSettingMTypeGetResponse,
    GroupV2GroupIdAdminAbdicateFoundershipMembershipTypeFounderIdNewPostResponse,
    GroupV2GroupIdAdminsAndFounderGetResponse,
    GroupV2GroupIdBannedGetResponse,
    GroupV2GroupIdEditClanBannerPostResponse,
    GroupV2GroupIdEditFounderOptionsPostResponse,
    GroupV2GroupIdEditPostResponse,
    GroupV2GroupIdGetResponse,
    GroupV2GroupIdMembersApproveAllPostResponse,
    GroupV2GroupIdMembersApproveListPostResponse,
    GroupV2GroupIdMembersApproveMembershipTypeMembershipIdPostResponse,
    GroupV2GroupIdMembersDenyAllPostResponse,
    GroupV2GroupIdMembersDenyListPostResponse,
    GroupV2GroupIdMembersGetResponse,
    GroupV2GroupIdMembersIndividualInviteCancelMembershipTypeMembershipIdPostResponse,
    GroupV2GroupIdMembersIndividualInviteMembershipTypeMembershipIdPostResponse,
    GroupV2GroupIdMembersInvitedIndividualsGetResponse,
    GroupV2GroupIdMembersMembershipTypeMembershipIdBanPostResponse,
    GroupV2GroupIdMembersMembershipTypeMembershipIdKickPostResponse,
    GroupV2GroupIdMembersMembershipTypeMembershipIdSetMembershipTypeMemberTypePostResponse,
    GroupV2GroupIdMembersMembershipTypeMembershipIdUnbanPostResponse,
    GroupV2GroupIdMembersPendingGetResponse,
    GroupV2GroupIdOptionalConversationsAddPostResponse,
    GroupV2GroupIdOptionalConversationsEditConversationIdPostResponse,
    GroupV2GroupIdOptionalConversationsGetResponse,
    GroupV2NameGroupNameGroupTypeGetResponse,
    GroupV2NameV2PostResponse,
    GroupV2RecommendedGroupTypeCreateDateRangePostResponse,
    GroupV2RecoverMembershipTypeMembershipIdGroupTypeGetResponse,
    GroupV2SearchPostResponse,
    GroupV2UserMembershipTypeMembershipIdFilterGroupTypeGetResponse,
    GroupV2UserPotentialMembershipTypeMembershipIdFilterGroupTypeGetResponse,
    Modes,
    SettingsGetResponse,
    SocialFriendsAddMembershipIdPostResponse,
    SocialFriendsGetResponse,
    SocialFriendsRemoveMembershipIdPostResponse,
    SocialFriendsRequestsAcceptMembershipIdPostResponse,
    SocialFriendsRequestsDeclineMembershipIdPostResponse,
    SocialFriendsRequestsGetResponse,
    SocialFriendsRequestsRemoveMembershipIdPostResponse,
    SocialPlatformFriendsFriendPlatformPageGetResponse,
    TokensPartnerApplyMissingOffersPartnerApplicationIdTargetBnetMembershipIdPostResponse,
    TokensPartnerClaimOfferPostResponse,
    TokensPartnerForceDropsRepairPostResponse,
    TokensPartnerHistoryPartnerApplicationIdTargetBnetMembershipIdGetResponse,
    TokensPartnerHistoryTargetBnetMembershipIdApplicationPartnerApplicationIdGetResponse,
    TokensRewardsBungieRewardsGetResponse,
    TokensRewardsGetRewardsForPlatformUserMembershipIdMembershipTypeGetResponse,
    TokensRewardsGetRewardsForUserMembershipIdGetResponse,
    TrendingCategoriesCategoryIdPageNumberGetResponse,
    TrendingCategoriesGetResponse,
    TrendingDetailsTrendingEntryTypeIdentifierGetResponse,
    UserGetAvailableThemesGetResponse,
    UserGetBungieNetUserByIdIdGetResponse,
    UserGetCredentialTypesForTargetAccountMembershipIdGetResponse,
    UserGetMembershipFromHardLinkedCredentialCrTypeCredentialGetResponse,
    UserGetMembershipsByIdMembershipIdMembershipTypeGetResponse,
    UserGetMembershipsForCurrentUserGetResponse,
    UserGetSanitizedPlatformDisplayNamesMembershipIdGetResponse,
    UserSearchGlobalNamePagePostResponse,
    UserSearchPrefixDisplayNamePrefixPageGetResponse,
    UserSystemOverridesGetResponse,
)

app = MCPProxy(
    contact={
        'email': 'support@bungie.com',
        'name': 'Bungie.net API Support',
        'url': 'https://github.com/Bungie-net/api',
    },
    description='These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.',
    license={
        'name': 'BSD License 2.0',
        'url': 'https://github.com/Bungie-net/api/blob/master/LICENSE',
    },
    termsOfService='https://www.bungie.net/en/View/Bungie/terms',
    title='Bungie.Net API',
    version='2.18.0',
    servers=[{'url': 'https://www.bungie.net/Platform'}],
)


@app.get(
    '/App/ApiUsage/{applicationId}/',
    description=""" Get API usage by application for time frame specified. You can go as far back as 30 days ago, and can ask for up to a 48 hour window of time in a single request. You must be authenticated with at least the ReadUserData permission to access this endpoint. """,
    tags=['application_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def app__get_application_api_usage(
    application_id: int = Path(..., alias='applicationId'),
    end: Optional[datetime] = None,
    start: Optional[datetime] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/App/FirstParty/',
    description=""" Get list of applications created by Bungie. """,
    tags=['application_management', 'user_account_management'],
)
def app__get_bungie_applications():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/CommunityContent/Get/{sort}/{mediaFilter}/{page}/',
    description=""" Returns community content. """,
    tags=['content_retrieval'],
)
def community_content__get_community_content(
    media_filter: int = Path(..., alias='mediaFilter'), page: int = ..., sort: int = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Content/GetContentById/{id}/{locale}/',
    description=""" Returns a content item referenced by id """,
    tags=['localization_services'],
)
def content__get_content_by_id(
    head: Optional[bool] = None, id: int = ..., locale: str = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Content/GetContentByTagAndType/{tag}/{type}/{locale}/',
    description=""" Returns the newest item that matches a given tag and Content Type. """,
    tags=['localization_services', 'membership_management'],
)
def content__get_content_by_tag_and_type(
    head: Optional[bool] = None, locale: str = ..., tag: str = ..., type: str = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Content/GetContentType/{type}/',
    description=""" Gets an object describing a particular variant of content. """,
    tags=['destiny2_manifest_access'],
)
def content__get_content_type(type: str):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Content/Rss/NewsArticles/{pageToken}/',
    description=""" Returns a JSON string response that is the RSS feed for news articles. """,
    tags=['content_retrieval'],
)
def content__rss_news_articles(
    categoryfilter: Optional[str] = None,
    includebody: Optional[bool] = None,
    page_token: str = Path(..., alias='pageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Content/Search/{locale}/',
    description=""" Gets content based on querystring information passed in. Provides basic search and text search capabilities. """,
    tags=['content_retrieval', 'localization_services'],
)
def content__search_content_with_text(
    ctype: Optional[str] = None,
    currentpage: Optional[int] = None,
    head: Optional[bool] = None,
    locale: str = ...,
    searchtext: Optional[str] = None,
    source: Optional[str] = None,
    tag: Optional[str] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Content/SearchContentByTagAndType/{tag}/{type}/{locale}/',
    description=""" Searches for Content Items that match the given Tag and Content Type. """,
    tags=['content_retrieval', 'localization_services'],
)
def content__search_content_by_tag_and_type(
    currentpage: Optional[int] = None,
    head: Optional[bool] = None,
    itemsperpage: Optional[int] = None,
    locale: str = ...,
    tag: str = ...,
    type: str = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Content/SearchHelpArticles/{searchtext}/{size}/',
    description=""" Search for Help Articles. """,
    tags=['content_retrieval'],
)
def content__search_help_articles(searchtext: str, size: str = ...):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/Actions/Items/EquipItem/',
    description=""" Equip an item. You must have a valid Destiny Account, and either be in a social space, in orbit, or offline. """,
    tags=['application_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def destiny2__equip_item():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/Actions/Items/EquipItems/',
    description=""" Equip a list of items by itemInstanceIds. You must have a valid Destiny Account, and either be in a social space, in orbit, or offline. Any items not found on your character will be ignored. """,
    tags=['membership_management', 'user_group_preferences'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def destiny2__equip_items():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/Actions/Items/InsertSocketPlug/',
    description=""" Insert a plug into a socketed item. I know how it sounds, but I assure you it's much more G-rated than you might be guessing. We haven't decided yet whether this will be able to insert plugs that have side effects, but if we do it will require special scope permission for an application attempting to do so. You must have a valid Destiny Account, and either be in a social space, in orbit, or offline. Request must include proof of permission for 'InsertPlugs' from the account owner. """,
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def destiny2__insert_socket_plug():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/Actions/Items/InsertSocketPlugFree/',
    description=""" Insert a 'free' plug into an item's socket. This does not require 'Advanced Write Action' authorization and is available to 3rd-party apps, but will only work on 'free and reversible' socket actions (Perks, Armor Mods, Shaders, Ornaments, etc.). You must have a valid Destiny Account, and the character must either be in a social space, in orbit, or offline. """,
    tags=['application_management', 'user_account_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def destiny2__insert_socket_plug_free():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/Actions/Items/PullFromPostmaster/',
    description=""" Extract an item from the Postmaster, with whatever implications that may entail. You must have a valid Destiny account. You must also pass BOTH a reference AND an instance ID if it's an instanced item. """,
    tags=['destiny2_user_authentication', 'user_account_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def destiny2__pull_from_postmaster():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/Actions/Items/SetLockState/',
    description=""" Set the Lock State for an instanced item. You must have a valid Destiny Account. """,
    tags=[
        'destiny2_item_handling',
        'destiny2_user_authentication',
        'destiny2_clan_operations',
        'destiny2_manifest_access',
        'milestone_tracking',
        'clan_performance_metrics',
        'player_activity_statistics',
        'profile_handling',
        'vendor_information',
        'fireteam_operations',
    ],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def destiny2__set_item_lock_state():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/Actions/Items/SetTrackedState/',
    description=""" Set the Tracking State for an instanced item, if that item is a Quest or Bounty. You must have a valid Destiny Account. Yeah, it's an item. """,
    tags=['application_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def destiny2__set_quest_tracked_state():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/Actions/Items/TransferItem/',
    description=""" Transfer an item to/from your vault. You must have a valid Destiny account. You must also pass BOTH a reference AND an instance ID if it's an instanced item. itshappening.gif """,
    tags=['application_management', 'user_account_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def destiny2__transfer_item():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/Actions/Loadouts/ClearLoadout/',
    description=""" Clear the identifiers and items of a loadout. """,
    tags=['application_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def destiny2__clear_loadout():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/Actions/Loadouts/EquipLoadout/',
    description=""" Equip a loadout. You must have a valid Destiny Account, and either be in a social space, in orbit, or offline. """,
    tags=['application_management', 'user_account_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def destiny2__equip_loadout():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/Actions/Loadouts/SnapshotLoadout/',
    description=""" Snapshot a loadout with the currently equipped items. """,
    tags=['application_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def destiny2__snapshot_loadout():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/Actions/Loadouts/UpdateLoadoutIdentifiers/',
    description=""" Update the color, icon, and name of a loadout. """,
    tags=['application_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def destiny2__update_loadout_identifiers():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/Armory/Search/{type}/{searchTerm}/',
    description=""" Gets a page list of Destiny items. """,
    tags=['content_retrieval', 'user_account_management'],
)
def destiny2__search_destiny_entities(
    page: Optional[int] = None,
    search_term: str = Path(..., alias='searchTerm'),
    type: str = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/Awa/AwaProvideAuthorizationResult/',
    description=""" Provide the result of the user interaction. Called by the Bungie Destiny App to approve or reject a request. """,
)
def destiny2__awa_provide_authorization_result():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/Awa/GetActionToken/{correlationId}/',
    description=""" Returns the action token if user approves the request. """,
    tags=['user_account_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def destiny2__awa_get_action_token(
    correlation_id: str = Path(..., alias='correlationId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/Awa/Initialize/',
    description=""" Initialize a request to perform an advanced write action. """,
    tags=[
        'destiny2_item_handling',
        'destiny2_user_authentication',
        'destiny2_clan_operations',
        'destiny2_manifest_access',
        'milestone_tracking',
        'clan_performance_metrics',
        'player_activity_statistics',
        'profile_handling',
        'vendor_information',
        'fireteam_operations',
        'forum_data_management',
        'forum_post_operations',
        'forum_topic_management',
        'group_operations',
        'group_recommendation',
        'user_group_preferences',
        'localization_services',
        'membership_management',
        'group_chat_management',
        'social_network_management',
        'reward_management',
        'user_account_management',
        'trending_content_management',
        'theme_preferences',
    ],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def destiny2__awa_initialize_request():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/Clan/ClanBannerDictionary/',
    description=""" Returns the dictionary of values for the Clan Banner """,
    tags=['destiny2_item_handling', 'destiny2_user_authentication'],
)
def destiny2__get_clan_banner_source():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/Clan/{groupId}/WeeklyRewardState/',
    description=""" Returns information on the weekly clan rewards and if the clan has earned them or not. Note that this will always report rewards as not redeemed. """,
    tags=['group_operations', 'membership_management', 'user_group_preferences'],
)
def destiny2__get_clan_weekly_reward_state(group_id: int = Path(..., alias='groupId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/Manifest/',
    description=""" Returns the current version of the manifest as a json object. """,
)
def destiny2__get_destiny_manifest():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/Manifest/{entityType}/{hashIdentifier}/',
    description=""" Returns the static definition of an entity of the given Type and hash identifier. Examine the API Documentation for the Type Names of entities that have their own definitions. Note that the return type will always *inherit from* DestinyDefinition, but the specific type returned will be the requested entity type if it can be found. Please don't use this as a chatty alternative to the Manifest database if you require large sets of data, but for simple and one-off accesses this should be handy. """,
    tags=['destiny2_manifest_access', 'profile_handling', 'membership_management'],
)
def destiny2__get_destiny_entity_definition(
    entity_type: str = Path(..., alias='entityType'),
    hash_identifier: int = Path(..., alias='hashIdentifier'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/Milestones/',
    description=""" Gets public information about currently available Milestones. """,
    tags=['application_management', 'user_account_management'],
)
def destiny2__get_public_milestones():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/Milestones/{milestoneHash}/Content/',
    description=""" Gets custom localized content for the milestone of the given hash, if it exists. """,
    tags=['milestone_tracking'],
)
def destiny2__get_public_milestone_content(
    milestone_hash: int = Path(..., alias='milestoneHash')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/SearchDestinyPlayerByBungieName/{membershipType}/',
    description=""" Returns a list of Destiny memberships given a global Bungie Display Name. This method will hide overridden memberships due to cross save. """,
    tags=['membership_management'],
)
def destiny2__search_destiny_player_by_bungie_name(
    membership_type: int = Path(..., alias='membershipType')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/Stats/AggregateClanStats/{groupId}/',
    description=""" Gets aggregated stats for a clan using the same categories as the clan leaderboards. PREVIEW: This endpoint is still in beta, and may experience rough edges. The schema is in final form, but there may be bugs that prevent desirable operation. """,
    tags=['group_operations', 'membership_management'],
)
def destiny2__get_clan_aggregate_stats(
    group_id: int = Path(..., alias='groupId'), modes: Optional[str] = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/Stats/Definition/',
    description=""" Gets historical stats definitions. """,
    tags=['social_network_management'],
)
def destiny2__get_historical_stats_definition():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/Stats/Leaderboards/Clans/{groupId}/',
    description=""" Gets leaderboards with the signed in user's friends and the supplied destinyMembershipId as the focus. PREVIEW: This endpoint is still in beta, and may experience rough edges. The schema is in final form, but there may be bugs that prevent desirable operation. """,
    tags=['group_operations', 'membership_management', 'user_group_preferences'],
)
def destiny2__get_clan_leaderboards(
    group_id: int = Path(..., alias='groupId'),
    maxtop: Optional[int] = None,
    modes: Optional[str] = None,
    statid: Optional[str] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/Stats/Leaderboards/{membershipType}/{destinyMembershipId}/{characterId}/',
    description=""" Gets leaderboards with the signed in user's friends and the supplied destinyMembershipId as the focus. PREVIEW: This endpoint is still in beta, and may experience rough edges. The schema is in final form, but there may be bugs that prevent desirable operation. """,
    tags=['destiny2_item_handling', 'player_activity_statistics', 'profile_handling'],
)
def destiny2__get_leaderboards_for_character(
    character_id: int = Path(..., alias='characterId'),
    destiny_membership_id: int = Path(..., alias='destinyMembershipId'),
    maxtop: Optional[int] = None,
    membership_type: int = Path(..., alias='membershipType'),
    modes: Optional[str] = None,
    statid: Optional[str] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/Stats/PostGameCarnageReport/{activityId}/',
    description=""" Gets the available post game carnage report for the activity ID. """,
    tags=[
        'destiny2_user_authentication',
        'membership_management',
        'user_group_preferences',
    ],
)
def destiny2__get_post_game_carnage_report(
    activity_id: int = Path(..., alias='activityId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Destiny2/Stats/PostGameCarnageReport/{activityId}/Report/',
    description=""" Report a player that you met in an activity that was engaging in ToS-violating activities. Both you and the offending player must have played in the activityId passed in. Please use this judiciously and only when you have strong suspicions of violation, pretty please. """,
    tags=['player_activity_statistics'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def destiny2__report_offensive_post_game_carnage_report_player(
    activity_id: int = Path(..., alias='activityId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/Vendors/',
    description=""" Get items available from vendors where the vendors have items for sale that are common for everyone. If any portion of the Vendor's available inventory is character or account specific, we will be unable to return their data from this endpoint due to the way that available inventory is computed. As I am often guilty of saying: 'It's a long story...' """,
    tags=['profile_handling', 'user_account_management'],
)
def destiny2__get_public_vendors(components: Optional[Components] = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/',
    description=""" Gets historical stats for indicated character. """,
    tags=[
        'player_activity_statistics',
        'profile_handling',
        'destiny2_user_authentication',
    ],
)
def destiny2__get_historical_stats(
    character_id: int = Path(..., alias='characterId'),
    dayend: Optional[datetime] = None,
    daystart: Optional[datetime] = None,
    destiny_membership_id: int = Path(..., alias='destinyMembershipId'),
    groups: Optional[Groups] = None,
    membership_type: int = Path(..., alias='membershipType'),
    modes: Optional[Modes] = None,
    period_type: Optional[int] = Query(None, alias='periodType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/Activities/',
    description=""" Gets activity history stats for indicated character. """,
    tags=['player_activity_statistics', 'profile_handling'],
)
def destiny2__get_activity_history(
    character_id: int = Path(..., alias='characterId'),
    count: Optional[int] = None,
    destiny_membership_id: int = Path(..., alias='destinyMembershipId'),
    membership_type: int = Path(..., alias='membershipType'),
    mode: Optional[int] = None,
    page: Optional[int] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/AggregateActivityStats/',
    description=""" Gets all activities the character has participated in together with aggregate statistics for those activities. """,
    tags=['profile_handling', 'player_activity_statistics'],
)
def destiny2__get_destiny_aggregate_activity_stats(
    character_id: int = Path(..., alias='characterId'),
    destiny_membership_id: int = Path(..., alias='destinyMembershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/UniqueWeapons/',
    description=""" Gets details about unique weapon usage, including all exotic weapons. """,
    tags=['destiny2_user_authentication', 'profile_handling'],
)
def destiny2__get_unique_weapon_history(
    character_id: int = Path(..., alias='characterId'),
    destiny_membership_id: int = Path(..., alias='destinyMembershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/{membershipType}/Account/{destinyMembershipId}/Stats/',
    description=""" Gets aggregate historical stats organized around each character for a given account. """,
    tags=['membership_management', 'user_group_preferences', 'group_operations'],
)
def destiny2__get_historical_stats_for_account(
    destiny_membership_id: int = Path(..., alias='destinyMembershipId'),
    groups: Optional[Groups] = None,
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/{membershipType}/Account/{destinyMembershipId}/Stats/Leaderboards/',
    description=""" Gets leaderboards with the signed in user's friends and the supplied destinyMembershipId as the focus. PREVIEW: This endpoint has not yet been implemented. It is being returned for a preview of future functionality, and for public comment/suggestion/preparation. """,
    tags=['destiny2_user_authentication', 'membership_management', 'profile_handling'],
)
def destiny2__get_leaderboards(
    destiny_membership_id: int = Path(..., alias='destinyMembershipId'),
    maxtop: Optional[int] = None,
    membership_type: int = Path(..., alias='membershipType'),
    modes: Optional[str] = None,
    statid: Optional[str] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/{membershipType}/Profile/{destinyMembershipId}/',
    description=""" Returns Destiny Profile information for the supplied membership. """,
    tags=['membership_management', 'destiny2_user_authentication', 'profile_handling'],
)
def destiny2__get_profile(
    components: Optional[Components] = None,
    destiny_membership_id: int = Path(..., alias='destinyMembershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/{membershipType}/Profile/{destinyMembershipId}/Character/{characterId}/',
    description=""" Returns character information for the supplied character. """,
    tags=['destiny2_item_handling', 'profile_handling', 'player_activity_statistics'],
)
def destiny2__get_character(
    character_id: int = Path(..., alias='characterId'),
    components: Optional[Components] = None,
    destiny_membership_id: int = Path(..., alias='destinyMembershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/{membershipType}/Profile/{destinyMembershipId}/Character/{characterId}/Collectibles/{collectiblePresentationNodeHash}/',
    description=""" Given a Presentation Node that has Collectibles as direct descendants, this will return item details about those descendants in the context of the requesting character. """,
    tags=['destiny2_item_handling', 'profile_handling', 'vendor_information'],
)
def destiny2__get_collectible_node_details(
    character_id: int = Path(..., alias='characterId'),
    collectible_presentation_node_hash: int = Path(
        ..., alias='collectiblePresentationNodeHash'
    ),
    components: Optional[Components] = None,
    destiny_membership_id: int = Path(..., alias='destinyMembershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/{membershipType}/Profile/{destinyMembershipId}/Character/{characterId}/Vendors/',
    description=""" Get currently available vendors from the list of vendors that can possibly have rotating inventory. Note that this does not include things like preview vendors and vendors-as-kiosks, neither of whom have rotating/dynamic inventories. Use their definitions as-is for those. """,
    tags=[
        'destiny2_user_authentication',
        'profile_handling',
        'player_activity_statistics',
    ],
)
def destiny2__get_vendors(
    character_id: int = Path(..., alias='characterId'),
    components: Optional[Components] = None,
    destiny_membership_id: int = Path(..., alias='destinyMembershipId'),
    filter: Optional[int] = None,
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/{membershipType}/Profile/{destinyMembershipId}/Character/{characterId}/Vendors/{vendorHash}/',
    description=""" Get the details of a specific Vendor. """,
    tags=['destiny2_item_handling', 'vendor_information', 'profile_handling'],
)
def destiny2__get_vendor(
    character_id: int = Path(..., alias='characterId'),
    components: Optional[Components] = None,
    destiny_membership_id: int = Path(..., alias='destinyMembershipId'),
    membership_type: int = Path(..., alias='membershipType'),
    vendor_hash: int = Path(..., alias='vendorHash'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/{membershipType}/Profile/{destinyMembershipId}/Item/{itemInstanceId}/',
    description=""" Retrieve the details of an instanced Destiny Item. An instanced Destiny item is one with an ItemInstanceId. Non-instanced items, such as materials, have no useful instance-specific details and thus are not queryable here. """,
    tags=['destiny2_item_handling', 'profile_handling'],
)
def destiny2__get_item(
    components: Optional[Components] = None,
    destiny_membership_id: int = Path(..., alias='destinyMembershipId'),
    item_instance_id: int = Path(..., alias='itemInstanceId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Destiny2/{membershipType}/Profile/{membershipId}/LinkedProfiles/',
    description=""" Returns a summary information about all profiles linked to the requesting membership type/membership ID that have valid Destiny information. The passed-in Membership Type/Membership ID may be a Bungie.Net membership or a Destiny membership. It only returns the minimal amount of data to begin making more substantive requests, but will hopefully serve as a useful alternative to UserServices for people who just care about Destiny data. Note that it will only return linked accounts whose linkages you are allowed to view. """,
    tags=['membership_management', 'group_operations'],
)
def destiny2__get_linked_profiles(
    get_all_memberships: Optional[bool] = Query(None, alias='getAllMemberships'),
    membership_id: int = Path(..., alias='membershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Fireteam/Clan/{groupId}/ActiveCount/',
    description=""" Gets a count of all active non-public fireteams for the specified clan. Maximum value returned is 25. """,
    tags=['group_operations', 'membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def fireteam__get_active_private_clan_fireteam_count(
    group_id: int = Path(..., alias='groupId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Fireteam/Clan/{groupId}/Available/{platform}/{activityType}/{dateRange}/{slotFilter}/{publicOnly}/{page}/',
    description=""" Gets a listing of all of this clan's fireteams that are have available slots. Caller is not checked for join criteria so caching is maximized. """,
    tags=['group_operations', 'membership_management', 'player_activity_statistics'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def fireteam__get_available_clan_fireteams(
    activity_type: int = Path(..., alias='activityType'),
    date_range: int = Path(..., alias='dateRange'),
    exclude_immediate: Optional[bool] = Query(None, alias='excludeImmediate'),
    group_id: int = Path(..., alias='groupId'),
    lang_filter: Optional[str] = Query(None, alias='langFilter'),
    page: int = ...,
    platform: int = ...,
    public_only: int = Path(..., alias='publicOnly'),
    slot_filter: int = Path(..., alias='slotFilter'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Fireteam/Clan/{groupId}/My/{platform}/{includeClosed}/{page}/',
    description=""" Gets a listing of all fireteams that caller is an applicant, a member, or an alternate of. """,
    tags=['group_operations', 'membership_management', 'user_group_preferences'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def fireteam__get_my_clan_fireteams(
    group_filter: Optional[bool] = Query(None, alias='groupFilter'),
    group_id: int = Path(..., alias='groupId'),
    include_closed: bool = Path(..., alias='includeClosed'),
    lang_filter: Optional[str] = Query(None, alias='langFilter'),
    page: int = ...,
    platform: int = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Fireteam/Clan/{groupId}/Summary/{fireteamId}/',
    description=""" Gets a specific fireteam. """,
    tags=['fireteam_operations', 'group_operations', 'membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def fireteam__get_clan_fireteam(
    fireteam_id: int = Path(..., alias='fireteamId'),
    group_id: int = Path(..., alias='groupId'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Fireteam/Search/Available/{platform}/{activityType}/{dateRange}/{slotFilter}/{page}/',
    description=""" Gets a listing of all public fireteams starting now with open slots. Caller is not checked for join criteria so caching is maximized. """,
    tags=['milestone_tracking', 'player_activity_statistics'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def fireteam__search_public_available_clan_fireteams(
    activity_type: int = Path(..., alias='activityType'),
    date_range: int = Path(..., alias='dateRange'),
    exclude_immediate: Optional[bool] = Query(None, alias='excludeImmediate'),
    lang_filter: Optional[str] = Query(None, alias='langFilter'),
    page: int = ...,
    platform: int = ...,
    slot_filter: int = Path(..., alias='slotFilter'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Forum/GetCoreTopicsPaged/{page}/{sort}/{quickDate}/{categoryFilter}/',
    description=""" Gets a listing of all topics marked as part of the core group. """,
    tags=['content_retrieval', 'localization_services'],
)
def forum__get_core_topics_paged(
    category_filter: int = Path(..., alias='categoryFilter'),
    locales: Optional[str] = None,
    page: int = ...,
    quick_date: int = Path(..., alias='quickDate'),
    sort: int = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Forum/GetForumTagSuggestions/',
    description=""" Gets tag suggestions based on partial text entry, matching them with other tags previously used in the forums. """,
    tags=['forum_topic_management', 'forum_data_management'],
)
def forum__get_forum_tag_suggestions(partialtag: Optional[str] = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Forum/GetPostAndParent/{childPostId}/',
    description=""" Returns the post specified and its immediate parent. """,
    tags=['forum_post_operations', 'forum_data_management'],
)
def forum__get_post_and_parent(
    child_post_id: int = Path(..., alias='childPostId'),
    showbanned: Optional[str] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Forum/GetPostAndParentAwaitingApproval/{childPostId}/',
    description=""" Returns the post specified and its immediate parent of posts that are awaiting approval. """,
    tags=['forum_post_operations'],
)
def forum__get_post_and_parent_awaiting_approval(
    child_post_id: int = Path(..., alias='childPostId'),
    showbanned: Optional[str] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Forum/GetPostsThreadedPaged/{parentPostId}/{page}/{pageSize}/{replySize}/{getParentPost}/{rootThreadMode}/{sortMode}/',
    description=""" Returns a thread of posts at the given parent, optionally returning replies to those posts as well as the original parent. """,
    tags=['forum_post_operations', 'forum_data_management'],
)
def forum__get_posts_threaded_paged(
    get_parent_post: bool = Path(..., alias='getParentPost'),
    page: int = ...,
    page_size: int = Path(..., alias='pageSize'),
    parent_post_id: int = Path(..., alias='parentPostId'),
    reply_size: int = Path(..., alias='replySize'),
    root_thread_mode: bool = Path(..., alias='rootThreadMode'),
    showbanned: Optional[str] = None,
    sort_mode: int = Path(..., alias='sortMode'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Forum/GetPostsThreadedPagedFromChild/{childPostId}/{page}/{pageSize}/{replySize}/{rootThreadMode}/{sortMode}/',
    description=""" Returns a thread of posts starting at the topicId of the input childPostId, optionally returning replies to those posts as well as the original parent. """,
    tags=['forum_post_operations', 'forum_data_management'],
)
def forum__get_posts_threaded_paged_from_child(
    child_post_id: int = Path(..., alias='childPostId'),
    page: int = ...,
    page_size: int = Path(..., alias='pageSize'),
    reply_size: int = Path(..., alias='replySize'),
    root_thread_mode: bool = Path(..., alias='rootThreadMode'),
    showbanned: Optional[str] = None,
    sort_mode: int = Path(..., alias='sortMode'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Forum/GetTopicForContent/{contentId}/',
    description=""" Gets the post Id for the given content item's comments, if it exists. """,
    tags=['content_retrieval', 'profile_handling'],
)
def forum__get_topic_for_content(content_id: int = Path(..., alias='contentId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Forum/GetTopicsPaged/{page}/{pageSize}/{group}/{sort}/{quickDate}/{categoryFilter}/',
    description=""" Get topics from any forum. """,
    tags=[
        'content_retrieval',
        'localization_services',
        'group_operations',
        'membership_management',
    ],
)
def forum__get_topics_paged(
    category_filter: int = Path(..., alias='categoryFilter'),
    group: int = ...,
    locales: Optional[str] = None,
    page: int = ...,
    page_size: int = Path(..., alias='pageSize'),
    quick_date: int = Path(..., alias='quickDate'),
    sort: int = ...,
    tagstring: Optional[str] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Forum/Poll/{topicId}/',
    description=""" Gets the specified forum poll. """,
    tags=['forum_topic_management', 'forum_data_management'],
)
def forum__get_poll(topic_id: int = Path(..., alias='topicId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Forum/Recruit/Summaries/',
    description=""" Allows the caller to get a list of to 25 recruitment thread summary information objects. """,
    tags=['none'],
)
def forum__get_recruitment_thread_summaries():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GetAvailableLocales/',
    description=""" List of available localization cultures """,
    tags=['application_management', 'user_account_management'],
)
def __get_available_locales():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GlobalAlerts/',
    description=""" Gets any active global alert for display in the forum banners, help pages, etc. Usually used for DOC alerts. """,
    tags=['membership_management', 'user_group_preferences'],
)
def __get_global_alerts(includestreaming: Optional[bool] = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GroupV2/GetAvailableAvatars/',
    description=""" Returns a list of all available group avatars for the signed-in user. """,
    tags=['application_management'],
)
def group_v2__get_available_avatars():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GroupV2/GetAvailableThemes/',
    description=""" Returns a list of all available group themes. """,
    tags=['application_management'],
)
def group_v2__get_available_themes():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GroupV2/GetUserClanInviteSetting/{mType}/',
    description=""" Gets the state of the user's clan invite preferences for a particular membership type - true if they wish to be invited to clans, false otherwise. """,
    tags=['membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__get_user_clan_invite_setting(m_type: int = Path(..., alias='mType')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GroupV2/Name/{groupName}/{groupType}/',
    description=""" Get information about a specific group with the given name and type. """,
    tags=['group_operations', 'membership_management'],
)
def group_v2__get_group_by_name(
    group_name: str = Path(..., alias='groupName'),
    group_type: int = Path(..., alias='groupType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/NameV2/',
    description=""" Get information about a specific group with the given name and type. The POST version. """,
    tags=[
        'destiny2_item_handling',
        'destiny2_user_authentication',
        'destiny2_clan_operations',
        'destiny2_manifest_access',
        'milestone_tracking',
        'clan_performance_metrics',
        'player_activity_statistics',
        'profile_handling',
        'vendor_information',
        'fireteam_operations',
        'forum_data_management',
        'forum_post_operations',
        'forum_topic_management',
        'group_operations',
        'group_recommendation',
        'user_group_preferences',
        'localization_services',
        'membership_management',
        'group_chat_management',
        'social_network_management',
        'reward_management',
        'user_account_management',
        'trending_content_management',
        'theme_preferences',
    ],
)
def group_v2__get_group_by_name_v2():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/Recommended/{groupType}/{createDateRange}/',
    description=""" Gets groups recommended for you based on the groups to whom those you follow belong. """,
    tags=['group_operations', 'membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__get_recommended_groups(
    create_date_range: int = Path(..., alias='createDateRange'),
    group_type: int = Path(..., alias='groupType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GroupV2/Recover/{membershipType}/{membershipId}/{groupType}/',
    description=""" Allows a founder to manually recover a group they can see in game but not on bungie.net """,
    tags=['membership_management', 'group_operations'],
)
def group_v2__recover_group_for_founder(
    group_type: int = Path(..., alias='groupType'),
    membership_id: int = Path(..., alias='membershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/Search/',
    description=""" Search for Groups. """,
    tags=['application_management', 'user_account_management'],
)
def group_v2__group_search():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GroupV2/User/Potential/{membershipType}/{membershipId}/{filter}/{groupType}/',
    description=""" Get information about the groups that a given member has applied to or been invited to. """,
    tags=['membership_management', 'group_operations'],
)
def group_v2__get_potential_groups_for_member(
    filter: int,
    group_type: int = Path(..., alias='groupType'),
    membership_id: int = Path(..., alias='membershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GroupV2/User/{membershipType}/{membershipId}/{filter}/{groupType}/',
    description=""" Get information about the groups that a given member has joined. """,
    tags=['membership_management', 'group_operations', 'user_group_preferences'],
)
def group_v2__get_groups_for_member(
    filter: int,
    group_type: int = Path(..., alias='groupType'),
    membership_id: int = Path(..., alias='membershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GroupV2/{groupId}/',
    description=""" Get information about a specific group of the given ID. """,
    tags=['group_operations', 'membership_management'],
)
def group_v2__get_group(group_id: int = Path(..., alias='groupId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/Admin/AbdicateFoundership/{membershipType}/{founderIdNew}/',
    description=""" An administrative method to allow the founder of a group or clan to give up their position to another admin permanently. """,
    tags=['group_operations', 'membership_management'],
)
def group_v2__abdicate_foundership(
    founder_id_new: int = Path(..., alias='founderIdNew'),
    group_id: int = Path(..., alias='groupId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GroupV2/{groupId}/AdminsAndFounder/',
    description=""" Get the list of members in a given group who are of admin level or higher. """,
    tags=['group_operations', 'membership_management'],
)
def group_v2__get_admins_and_founder_of_group(
    currentpage: int, group_id: int = Path(..., alias='groupId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GroupV2/{groupId}/Banned/',
    description=""" Get the list of banned members in a given group. Only accessible to group Admins and above. Not applicable to all groups. Check group features. """,
    tags=['group_operations', 'membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__get_banned_members_of_group(
    currentpage: int, group_id: int = Path(..., alias='groupId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/Edit/',
    description=""" Edit an existing group. You must have suitable permissions in the group to perform this operation. This latest revision will only edit the fields you pass in - pass null for properties you want to leave unaltered. """,
    tags=['group_operations', 'membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__edit_group(group_id: int = Path(..., alias='groupId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/EditClanBanner/',
    description=""" Edit an existing group's clan banner. You must have suitable permissions in the group to perform this operation. All fields are required. """,
    tags=['group_operations', 'membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__edit_clan_banner(group_id: int = Path(..., alias='groupId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/EditFounderOptions/',
    description=""" Edit group options only available to a founder. You must have suitable permissions in the group to perform this operation. """,
    tags=['group_operations', 'membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__edit_founder_options(group_id: int = Path(..., alias='groupId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GroupV2/{groupId}/Members/',
    description=""" Get the list of members in a given group. """,
    tags=['group_operations', 'membership_management', 'user_group_preferences'],
)
def group_v2__get_members_of_group(
    currentpage: int,
    group_id: int = Path(..., alias='groupId'),
    member_type: Optional[int] = Query(None, alias='memberType'),
    name_search: Optional[str] = Query(None, alias='nameSearch'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/Members/Approve/{membershipType}/{membershipId}/',
    description=""" Approve the given membershipId to join the group/clan as long as they have applied. """,
    tags=['membership_management', 'group_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__approve_pending(
    group_id: int = Path(..., alias='groupId'),
    membership_id: int = Path(..., alias='membershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/Members/ApproveAll/',
    description=""" Approve all of the pending users for the given group. """,
    tags=['group_operations', 'membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__approve_all_pending(group_id: int = Path(..., alias='groupId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/Members/ApproveList/',
    description=""" Approve all of the pending users for the given group. """,
    tags=['group_operations', 'membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__approve_pending_for_list(group_id: int = Path(..., alias='groupId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/Members/DenyAll/',
    description=""" Deny all of the pending users for the given group. """,
    tags=['group_operations', 'membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__deny_all_pending(group_id: int = Path(..., alias='groupId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/Members/DenyList/',
    description=""" Deny all of the pending users for the given group that match the passed-in . """,
    tags=['group_operations', 'membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__deny_pending_for_list(group_id: int = Path(..., alias='groupId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/Members/IndividualInvite/{membershipType}/{membershipId}/',
    description=""" Invite a user to join this group. """,
    tags=['membership_management', 'group_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__individual_group_invite(
    group_id: int = Path(..., alias='groupId'),
    membership_id: int = Path(..., alias='membershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/Members/IndividualInviteCancel/{membershipType}/{membershipId}/',
    description=""" Cancels a pending invitation to join a group. """,
    tags=['membership_management', 'group_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__individual_group_invite_cancel(
    group_id: int = Path(..., alias='groupId'),
    membership_id: int = Path(..., alias='membershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GroupV2/{groupId}/Members/InvitedIndividuals/',
    description=""" Get the list of users who have been invited into the group. """,
    tags=['group_operations', 'membership_management', 'user_group_preferences'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__get_invited_individuals(
    currentpage: int, group_id: int = Path(..., alias='groupId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GroupV2/{groupId}/Members/Pending/',
    description=""" Get the list of users who are awaiting a decision on their application to join a given group. Modified to include application info. """,
    tags=['group_operations', 'membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__get_pending_memberships(
    currentpage: int, group_id: int = Path(..., alias='groupId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/Members/{membershipType}/{membershipId}/Ban/',
    description=""" Bans the requested member from the requested group for the specified period of time. """,
    tags=['membership_management', 'group_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__ban_member(
    group_id: int = Path(..., alias='groupId'),
    membership_id: int = Path(..., alias='membershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/Members/{membershipType}/{membershipId}/Kick/',
    description=""" Kick a member from the given group, forcing them to reapply if they wish to re-join the group. You must have suitable permissions in the group to perform this operation. """,
    tags=['membership_management', 'group_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__kick_member(
    group_id: int = Path(..., alias='groupId'),
    membership_id: int = Path(..., alias='membershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/Members/{membershipType}/{membershipId}/SetMembershipType/{memberType}/',
    description=""" Edit the membership type of a given member. You must have suitable permissions in the group to perform this operation. """,
    tags=['membership_management', 'group_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__edit_group_membership(
    group_id: int = Path(..., alias='groupId'),
    membership_id: int = Path(..., alias='membershipId'),
    membership_type: int = Path(..., alias='membershipType'),
    member_type: int = Path(..., alias='memberType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/Members/{membershipType}/{membershipId}/Unban/',
    description=""" Unbans the requested member, allowing them to re-apply for membership. """,
    tags=['membership_management', 'group_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__unban_member(
    group_id: int = Path(..., alias='groupId'),
    membership_id: int = Path(..., alias='membershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/GroupV2/{groupId}/OptionalConversations/',
    description=""" Gets a list of available optional conversation channels and their settings. """,
    tags=['group_operations', 'membership_management'],
)
def group_v2__get_group_optional_conversations(
    group_id: int = Path(..., alias='groupId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/OptionalConversations/Add/',
    description=""" Add a new optional conversation/chat channel. Requires admin permissions to the group. """,
    tags=['group_operations', 'membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__add_optional_conversation(group_id: int = Path(..., alias='groupId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GroupV2/{groupId}/OptionalConversations/Edit/{conversationId}/',
    description=""" Edit the settings of an optional conversation/chat channel. Requires admin permissions to the group. """,
    tags=['group_operations', 'membership_management', 'group_chat_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def group_v2__edit_optional_conversation(
    conversation_id: int = Path(..., alias='conversationId'),
    group_id: int = Path(..., alias='groupId'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Settings/',
    description=""" Get the common settings used by the Bungie.Net environment. """,
    tags=['application_management'],
)
def __get_common_settings():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Social/Friends/',
    description=""" Returns your Bungie Friend list """,
    tags=['application_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def social__get_friend_list():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Social/Friends/Add/{membershipId}/',
    description=""" Requests a friend relationship with the target user. Any of the target user's linked membership ids are valid inputs. """,
    tags=['membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def social__issue_friend_request(membership_id: str = Path(..., alias='membershipId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Social/Friends/Remove/{membershipId}/',
    description=""" Remove a friend relationship with the target user. The user must be on your friend list, though no error will occur if they are not. """,
    tags=['membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def social__remove_friend(membership_id: str = Path(..., alias='membershipId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Social/Friends/Requests/',
    description=""" Returns your friend request queue. """,
    tags=['application_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def social__get_friend_request_list():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Social/Friends/Requests/Accept/{membershipId}/',
    description=""" Accepts a friend relationship with the target user. The user must be on your incoming friend request list, though no error will occur if they are not. """,
    tags=['membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def social__accept_friend_request(membership_id: str = Path(..., alias='membershipId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Social/Friends/Requests/Decline/{membershipId}/',
    description=""" Declines a friend relationship with the target user. The user must be on your incoming friend request list, though no error will occur if they are not. """,
    tags=['membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def social__decline_friend_request(
    membership_id: str = Path(..., alias='membershipId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Social/Friends/Requests/Remove/{membershipId}/',
    description=""" Remove a friend relationship with the target user. The user must be on your outgoing request friend list, though no error will occur if they are not. """,
    tags=['membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def social__remove_friend_request(membership_id: str = Path(..., alias='membershipId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Social/PlatformFriends/{friendPlatform}/{page}/',
    description=""" Gets the platform friend of the requested type, with additional information if they have Bungie accounts. Must have a recent login session with said platform. """,
    tags=[
        'social_network_management',
        'user_group_preferences',
        'membership_management',
    ],
)
def social__get_platform_friend_list(
    friend_platform: int = Path(..., alias='friendPlatform'), page: str = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Tokens/Partner/ApplyMissingOffers/{partnerApplicationId}/{targetBnetMembershipId}/',
    description=""" Apply a partner offer to the targeted user. This endpoint does not claim a new offer, but any already claimed offers will be applied to the game if not already. """,
    tags=['membership_management', 'group_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def tokens__apply_missing_partner_offers_without_claim(
    partner_application_id: int = Path(..., alias='partnerApplicationId'),
    target_bnet_membership_id: int = Path(..., alias='targetBnetMembershipId'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Tokens/Partner/ClaimOffer/',
    description=""" Claim a partner offer as the authenticated user. """,
    tags=['application_management', 'user_account_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def tokens__claim_partner_offer():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Tokens/Partner/ForceDropsRepair/',
    description=""" Twitch Drops self-repair function - scans twitch for drops not marked as fulfilled and resyncs them. """,
    tags=['application_management', 'user_account_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def tokens__force_drops_repair():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Tokens/Partner/History/{partnerApplicationId}/{targetBnetMembershipId}/',
    description=""" Returns the partner sku and offer history of the targeted user. Elevated permissions are required to see users that are not yourself. """,
    tags=['membership_management', 'user_group_preferences'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def tokens__get_partner_offer_sku_history(
    partner_application_id: int = Path(..., alias='partnerApplicationId'),
    target_bnet_membership_id: int = Path(..., alias='targetBnetMembershipId'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Tokens/Partner/History/{targetBnetMembershipId}/Application/{partnerApplicationId}/',
    description=""" Returns the partner rewards history of the targeted user, both partner offers and Twitch drops. """,
    tags=['membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def tokens__get_partner_reward_history(
    partner_application_id: int = Path(..., alias='partnerApplicationId'),
    target_bnet_membership_id: int = Path(..., alias='targetBnetMembershipId'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Tokens/Rewards/BungieRewards/',
    description=""" Returns a list of the current bungie rewards """,
    tags=['application_management'],
)
def tokens__get_bungie_rewards_list():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Tokens/Rewards/GetRewardsForPlatformUser/{membershipId}/{membershipType}/',
    description=""" Returns the bungie rewards for the targeted user when a platform membership Id and Type are used. """,
    tags=['membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def tokens__get_bungie_rewards_for_platform_user(
    membership_id: int = Path(..., alias='membershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Tokens/Rewards/GetRewardsForUser/{membershipId}/',
    description=""" Returns the bungie rewards for the targeted user. """,
    tags=['membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def tokens__get_bungie_rewards_for_user(
    membership_id: int = Path(..., alias='membershipId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Trending/Categories/',
    description=""" Returns trending items for Bungie.net, collapsed into the first page of items per category. For pagination within a category, call GetTrendingCategory. """,
    tags=['application_management', 'content_retrieval'],
)
def trending__get_trending_categories():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Trending/Categories/{categoryId}/{pageNumber}/',
    description=""" Returns paginated lists of trending items for a category. """,
    tags=['content_retrieval'],
)
def trending__get_trending_category(
    category_id: str = Path(..., alias='categoryId'),
    page_number: int = Path(..., alias='pageNumber'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Trending/Details/{trendingEntryType}/{identifier}/',
    description=""" Returns the detailed results for a specific trending entry. Note that trending entries are uniquely identified by a combination of *both* the TrendingEntryType *and* the identifier: the identifier alone is not guaranteed to be globally unique. """,
    tags=['trending_content_management'],
)
def trending__get_trending_entry_detail(
    identifier: str, trending_entry_type: int = Path(..., alias='trendingEntryType')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/User/GetAvailableThemes/',
    description=""" Returns a list of all available user themes. """,
    tags=[
        'application_management',
        'destiny2_user_authentication',
        'user_account_management',
    ],
)
def user__get_available_themes():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/User/GetBungieNetUserById/{id}/',
    description=""" Loads a bungienet user by membership id. """,
    tags=['destiny2_user_authentication'],
)
def user__get_bungie_net_user_by_id(id: int):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/User/GetCredentialTypesForTargetAccount/{membershipId}/',
    description=""" Returns a list of credential types attached to the requested account """,
    tags=['membership_management'],
)
def user__get_credential_types_for_target_account(
    membership_id: int = Path(..., alias='membershipId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/User/GetMembershipFromHardLinkedCredential/{crType}/{credential}/',
    description=""" Gets any hard linked membership given a credential. Only works for credentials that are public (just SteamID64 right now). Cross Save aware. """,
    tags=['destiny2_user_authentication'],
)
def user__get_membership_from_hard_linked_credential(
    credential: str, cr_type: int = Path(..., alias='crType')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/User/GetMembershipsById/{membershipId}/{membershipType}/',
    description=""" Returns a list of accounts associated with the supplied membership ID and membership type. This will include all linked accounts (even when hidden) if supplied credentials permit it. """,
    tags=['membership_management'],
)
def user__get_membership_data_by_id(
    membership_id: int = Path(..., alias='membershipId'),
    membership_type: int = Path(..., alias='membershipType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/User/GetMembershipsForCurrentUser/',
    description=""" Returns a list of accounts associated with signed in user. This is useful for OAuth implementations that do not give you access to the token response. """,
    tags=['application_management', 'membership_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def user__get_membership_data_for_current_user():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/User/GetSanitizedPlatformDisplayNames/{membershipId}/',
    description=""" Gets a list of all display names linked to this membership id but sanitized (profanity filtered). Obeys all visibility rules of calling user and is heavily cached. """,
    tags=['membership_management'],
)
def user__get_sanitized_platform_display_names(
    membership_id: int = Path(..., alias='membershipId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/User/Search/GlobalName/{page}/',
    description=""" Given the prefix of a global display name, returns all users who share that name. """,
    tags=['destiny2_manifest_access', 'content_retrieval'],
)
def user__search_by_global_name_post(page: int):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/User/Search/Prefix/{displayNamePrefix}/{page}/',
    description=""" [OBSOLETE] Do not use this to search users, use SearchByGlobalNamePost instead. """,
    tags=['user_account_management'],
)
def user__search_by_global_name_prefix(
    display_name_prefix: str = Path(..., alias='displayNamePrefix'), page: int = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/UserSystemOverrides/',
    description=""" Get the user-specific system overrides that should be respected alongside common systems. """,
    tags=['application_management'],
)
def __get_user_system_overrides():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
